(() => {
  "use strict";

  const createEffect = (
    id,
    nameJa,
    nameEn,
    modName,
    category,
    description,
    options = {},
  ) => ({
    id,
    nameJa,
    nameEn,
    modName,
    category,
    color: options.color ?? "未確認",
    instant: Boolean(options.instant),
    description,
    scaling: options.scaling ?? "Lvによる変化は未確認",
    duration: options.duration ?? "付与時の効果時間に依存",
    maxLevel: options.maxLevel ?? "未確認",
    cures: options.cures ?? ["牛乳（vanillaの通常効果）"],
    potion: options.potion ?? "通常ポーションは未確認",
    brewing: options.brewing ?? "専用の醸造レシピは未確認",
    beacon: options.beacon ?? "不可 / 未確認",
    charm: options.charm ?? "未確認",
    charmNote: options.charmNote ?? "ATM10 8.2の既存Charmデータで、この効果の常時付与は確認できず",
    technical: Boolean(options.technical),
    confidence: options.confidence ?? "confirmed",
    source: options.source ?? "ATM10 8.2対象jarの登録・lang・クラス実装を照合",
  });

  const vanilla = [
    ["absorption", "衝撃吸収", "Absorption", "有益", "体力バーの上に黄色い追加ハートを与え、追加ハートが先にダメージを受ける。", { scaling: "Lvが上がるほど追加ハートが増える", maxLevel: "IV", potion: "通常ポーションなし", brewing: "醸造不可", charm: "既存装備", charmNote: "Artifacts / Reliquified Artifacts系の装備能力で付与される個別アイテムを確認" }],
    ["bad_omen", "不吉な予感", "Bad Omen", "中立", "村に入ると襲撃を開始し、試練の間では不吉な瓶の効果に応じた試練を誘発する。", { scaling: "Lvが上がるほど襲撃・試練の難度に影響", maxLevel: "V", potion: "不吉な瓶", brewing: "醸造不可", charm: "未確認", technical: false }],
    ["blindness", "盲目", "Blindness", "有害", "視界を大きく狭め、遠方や暗い場所を見えにくくする。", { potion: "通常ポーションなし", charm: "未確認" }],
    ["conduit_power", "コンジットパワー", "Conduit Power", "有益", "水中での視界・採掘・呼吸を改善し、コンジットの範囲内で水中活動を強化する。", { duration: "コンジットの有効範囲内で継続", maxLevel: "I", potion: "通常ポーションなし", brewing: "コンジットから付与", charm: "未確認" }],
    ["darkness", "暗闇", "Darkness", "有害", "画面の明るさを周期的に下げ、周囲をほとんど見えなくする。", { potion: "通常ポーションなし", charm: "未確認" }],
    ["dolphins_grace", "イルカの好意", "Dolphin's Grace", "有益", "イルカの近くで泳ぐときの水中移動速度を大幅に上げる。", { maxLevel: "I", potion: "通常ポーションなし", charm: "未確認" }],
    ["fire_resistance", "火炎耐性", "Fire Resistance", "有益", "火・溶岩・マグマブロックなどの火属性ダメージを無効化する。", { maxLevel: "I", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Artifactsの火炎系装備能力など、個別装備からの付与を確認" }],
    ["glowing", "発光", "Glowing", "有益", "壁越しでも見える輪郭線を対象に表示する。", { maxLevel: "I", potion: "通常ポーションなし", charm: "未確認" }],
    ["haste", "採掘速度上昇", "Haste", "有益", "ブロックの採掘速度を上げる。適正ツール使用時は採掘時間が短くなる。", { scaling: "Lvが上がるほど採掘速度が上昇", maxLevel: "II", potion: "通常ポーションなし", brewing: "醸造不可", charm: "既存装備", charmNote: "Artifacts / Relics系の装備効果に近いが、全件の常時付与は未確認" }],
    ["health_boost", "体力増強", "Health Boost", "有益", "最大体力を増やし、増加分の体力も同時に追加する。", { scaling: "Lvごとに最大体力が増える", maxLevel: "II", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
    ["hero_of_the_village", "村の英雄", "Hero of the Village", "有益", "村人との取引価格を下げ、村人から贈り物を受け取れるようにする。", { scaling: "Lvが上がるほど取引割引が強くなる", potion: "通常ポーションなし", brewing: "襲撃勝利で付与", charm: "未確認" }],
    ["hunger", "空腹", "Hunger", "有害", "満腹度と隠し満腹度を通常より速く減らす。", { scaling: "Lvが上がるほど満腹度の減少が速くなる", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
    ["infested", "虫入り", "Infested", "中立", "ダメージを受けるとシルバーフィッシュを発生させることがある。", { scaling: "Lvによる発生挙動は固定データではなく付与側に依存", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["instant_damage", "負傷", "Instant Damage", "有害", "付与された瞬間に即時ダメージを与える。アンデッドには回復として作用する。", { instant: true, scaling: "Lvが上がるほど即時ダメージ量が増える", maxLevel: "II", duration: "瞬間効果", potion: "あり", brewing: "あり", charm: "未確認" }],
    ["instant_health", "治癒", "Instant Health", "有益", "付与された瞬間に体力を回復する。アンデッドにはダメージとして作用する。", { instant: true, scaling: "Lvが上がるほど即時回復量が増える", maxLevel: "II", duration: "瞬間効果", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "装備の発動時回復としては存在するが、常時Charm化ではない" }],
    ["invisibility", "透明化", "Invisibility", "有益", "プレイヤーやMobの姿を見えなくする。防具・持ち物・発射体などは見える場合がある。", { maxLevel: "I", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Scarf of Invisibilityなど、条件付きで装備から付与" }],
    ["jump_boost", "跳躍力上昇", "Jump Boost", "有益", "ジャンプ高度を上げ、落下ダメージを軽減する。", { scaling: "Lvが上がるほどジャンプ高度と落下耐性が上昇", maxLevel: "II", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "装備能力での付与を確認できるが、全Charmへの変換ではない" }],
    ["levitation", "浮遊", "Levitation", "有害", "対象を空中へ押し上げ、通常の歩行やジャンプをできなくする。", { scaling: "Lvが上がるほど上昇速度が増える", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["luck", "幸運", "Luck", "有益", "幸運属性を使う釣りや一部のランダムな抽選結果を有利にする。", { scaling: "Lvが上がるほど幸運値が上昇", maxLevel: "I", potion: "通常ポーションなし", brewing: "醸造不可", charm: "既存装備", charmNote: "Lucky Scarf等の装備効果での利用を確認" }],
    ["mining_fatigue", "採掘速度低下", "Mining Fatigue", "有害", "ブロックの採掘速度を下げ、破壊に必要な時間を大きく増やす。", { scaling: "Lvが上がるほど採掘速度が低下", maxLevel: "III", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
    ["nausea", "吐き気", "Nausea", "有害", "画面を歪ませ、視界の中心が周期的に揺れる。", { maxLevel: "I", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
    ["night_vision", "暗視", "Night Vision", "有益", "暗い場所を昼間のように明るく見られる。", { maxLevel: "I", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Night Vision Gogglesなどの常時・切替式装備で付与" }],
    ["oozing", "滲出", "Oozing", "中立", "対象が死亡したとき、スライムを発生させる。", { scaling: "Lvによる発生数の差は付与側に依存", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["poison", "毒", "Poison", "有害", "一定間隔でダメージを与えるが、体力を1未満にはしない。", { scaling: "Lvが上がるほどダメージ間隔・量が強化される", maxLevel: "II", potion: "あり", brewing: "あり", charm: "未確認" }],
    ["raid_omen", "襲撃の予感", "Raid Omen", "中立", "村に入ると襲撃を開始するまでの予告状態になる。", { maxLevel: "V", potion: "不吉な瓶から付与", brewing: "醸造不可", charm: "未確認" }],
    ["regeneration", "再生", "Regeneration", "有益", "時間経過で体力を回復する。", { scaling: "Lvが上がるほど回復間隔が短くなる", maxLevel: "II", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Crystal Heartなど、装備側が発動時に付与する例を確認" }],
    ["resistance", "耐性", "Resistance", "有益", "多くのダメージを割合で軽減する。", { scaling: "Lvが上がるほど軽減量が増える", maxLevel: "IV", potion: "通常ポーションなし", brewing: "醸造不可", charm: "既存装備", charmNote: "防具・Relics系の装備効果で付与される例を確認" }],
    ["saturation", "満腹度回復", "Saturation", "有益", "満腹度と隠し満腹度を即座に回復する。", { instant: true, scaling: "Lvが上がるほど回復量が増える", duration: "瞬間効果", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["slow_falling", "低速落下", "Slow Falling", "有益", "落下速度を下げ、落下ダメージを無効化する。", { maxLevel: "I", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "装備の落下保護能力としては確認できるが、常時Charm化の共通レシピは未確認" }],
    ["slowness", "鈍化", "Slowness", "有害", "歩行速度を低下させる。", { scaling: "Lvが上がるほど移動速度が低下", maxLevel: "IV", potion: "あり", brewing: "あり", charm: "未確認" }],
    ["speed", "移動速度上昇", "Speed", "有益", "歩行・走行速度を上げる。", { scaling: "Lvが上がるほど移動速度が上昇", maxLevel: "II", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Running Shoesなど、装備側の速度能力として存在" }],
    ["strength", "攻撃力上昇", "Strength", "有益", "近接攻撃のダメージを増やす。", { scaling: "Lvが上がるほど近接攻撃力が増える", maxLevel: "II", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "攻撃系装備の能力として付与される例を確認" }],
    ["trial_omen", "試練の予感", "Trial Omen", "中立", "試練の間で不吉な試練を開始する予告状態になる。", { maxLevel: "V", potion: "不吉な瓶から付与", brewing: "醸造不可", charm: "未確認" }],
    ["unluck", "不運", "Bad Luck", "有害", "幸運属性を使う抽選の結果を不利にする。", { scaling: "Lvが上がるほど幸運値が低下", maxLevel: "I", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
    ["water_breathing", "水中呼吸", "Water Breathing", "有益", "水中で酸素ゲージが減らなくなる。", { maxLevel: "I", potion: "あり", brewing: "あり", charm: "既存装備", charmNote: "Snorkelなど、水中装備の常時付与を確認" }],
    ["weakness", "弱体化", "Weakness", "有害", "近接攻撃のダメージを減らす。", { scaling: "Lvが上がるほど攻撃力が低下", potion: "あり", brewing: "あり", charm: "未確認" }],
    ["weaving", "紡績", "Weaving", "中立", "死亡時にクモの巣を生成し、クモの巣を通り抜けやすくする。", { scaling: "Lvによる挙動差は付与側に依存", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["wind_charged", "風力", "Wind Charged", "中立", "死亡時に風の爆発を起こし、周囲のエンティティを吹き飛ばす。", { scaling: "Lvによる爆発規模の差は付与側に依存", potion: "通常ポーションなし", brewing: "通常醸造不可", charm: "未確認" }],
    ["wither", "衰弱", "Wither", "有害", "一定間隔でダメージを与え、体力を0まで減らせる。", { scaling: "Lvが上がるほどダメージ量が増える", maxLevel: "I", potion: "通常ポーションなし", brewing: "醸造不可", charm: "未確認" }],
  ].map(([id, ja, en, category, description, options]) => createEffect(`minecraft:${id}`, ja, en, "Minecraft", category, description, options));

  const custom = [
    ["ars_nouveau:blasting", "爆破", "Blasting", "Ars Nouveau", "有害", "効果時間が切れたとき、対象を中心に爆発を起こす。", { scaling: "爆発の強さは効果の付与側に依存", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:bounce", "反発", "Bounce", "Ars Nouveau", "中立", "地面や壁に触れたエンティティを跳ね返す。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:flight", "飛行", "Flight", "Ars Nouveau", "有益", "プレイヤーに飛行能力を与える。", { maxLevel: "I", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:freezing", "凍結", "Freezing", "Ars Nouveau", "有害", "対象を時間経過で凍らせ、移動や行動を制限する。", { scaling: "Lvによる凍結速度は付与側に依存", potion: "あり", brewing: "Abjuration Essence＋Frostaya Pod系", charm: "未確認" }],
    ["ars_nouveau:glide", "滑空", "Glide", "Ars Nouveau", "有益", "エリトラを装備したように空中を滑空できる。", { maxLevel: "I", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:gravity", "重力増加", "Gravity", "Ars Nouveau", "有害", "対象を急速に落下させる。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:hex", "呪い", "Hex", "Ars Nouveau", "有害", "ポーション由来とプレイヤー以外から受けるダメージを増加させる。", { scaling: "Lvが上がるほど被ダメージ増加が強化", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:immolate", "焼却", "Immolate", "Ars Nouveau", "有益", "火属性のスペルを強化する。", { scaling: "スペル側の効果量に依存", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:looting", "ドライグミーの祝福", "Drygmy's Blessing", "Ars Nouveau", "有益", "周囲のMobから得られるドロップ量を増やす。", { scaling: "Lvが上がるほどドロップ増加が強化", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:magic_find", "魔法探知", "Magic Find", "Ars Nouveau", "有益", "近くにいる魔法的なエンティティを発光させる。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:mana_regen", "マナ再生", "Mana Regeneration", "Ars Nouveau", "有益", "Ars Nouveauのマナ回復速度を高める。", { scaling: "Lvが上がるほどマナ回復が強化", potion: "あり", brewing: "Abjuration Essence＋Sourceberry Bush系", charm: "未確認" }],
    ["ars_nouveau:recovery", "回復強化", "Recovery", "Ars Nouveau", "有益", "あらゆる手段から受ける回復量を増やす。", { scaling: "Lvが上がるほど回復量が増える", potion: "あり", brewing: "Abjuration Essence＋Mendosteen Pod系", charm: "未確認" }],
    ["ars_nouveau:scrying", "透視", "Scrying", "Ars Nouveau", "有益", "周囲にある特定のブロックを見つけやすくする。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:shielding", "魔法障壁", "Shielding", "Ars Nouveau", "有益", "受けるダメージ量を減らす。", { scaling: "Lvが上がるほどダメージ軽減が強化", potion: "あり", brewing: "Abjuration Essence＋Bastion Pod系", charm: "未確認" }],
    ["ars_nouveau:shocked", "感電", "Shocked", "Ars Nouveau", "有害", "雷属性のダメージを受けやすくする。", { scaling: "Lvが上がるほど雷ダメージ増加が強化", potion: "なし", charm: "未確認" }],
    ["ars_nouveau:snared", "拘束", "Snared", "Ars Nouveau", "有害", "対象の移動を完全に防ぐ。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:soaked", "水浸し", "Soaked", "Ars Nouveau", "中立", "対象を濡らし、火から守り、他の水系効果を発動しやすくする。", { potion: "なし", charm: "未確認" }],
    ["ars_nouveau:spell_damage", "スペルダメージ", "Spell Damage", "Ars Nouveau", "有益", "スペルが与えるダメージを増加させる。", { scaling: "Lvが上がるほどスペルダメージが増える", potion: "あり", brewing: "Abjuration Essence＋Magebloom系", charm: "未確認" }],
    ["ars_nouveau:summoning_sickness", "召喚酔い", "Summoning Sickness", "Ars Nouveau", "有害", "短時間、召喚を行えなくする。", { duration: "召喚後の短時間", potion: "なし", charm: "未確認" }],
    ["ars_elemental:enderference", "エンダー干渉", "Enderference", "Ars Elemental", "有害", "対象のテレポートを防ぎ、対象をテレポートさせることもできなくする。", { potion: "あり", brewing: "通常・延長ポーションあり", charm: "未確認" }],
    ["ars_elemental:enthralled", "魅了", "Enthralled", "Ars Elemental", "有益", "Mobが付与者を攻撃せず、付与者を守るように振る舞う。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:frozen", "凍結状態", "Frozen", "Ars Elemental", "有害", "対象を凍らせて回復できなくし、次に受ける火属性ダメージを増やす。ただし火属性ダメージで解除される。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:hellfire", "魔法の炎", "Magic Burn", "Ars Elemental", "有害", "魔法の炎で燃やし、ネザー系Mobにも火の影響を与える。土属性ダメージを弱め、魔法ダメージが防具を貫通しやすくなる。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:hymn_of_order", "秩序の聖歌", "Hymn of Order", "Ars Elemental", "中立", "管理者向けの未入手ポーション用効果。通常プレイでの入手を想定していない。", { potion: "管理者用・通常入手不可", brewing: "醸造不可", charm: "未確認", technical: true }],
    ["ars_elemental:life_link", "生命リンク", "Life Linked", "Ars Elemental", "中立", "付与者と対象の被ダメージ・回復を分け合う。Cut系の効果で双方のリンクを解除できる。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:mana_shield", "マナシールド", "Mana Shield", "Ars Elemental", "有益", "マナを消費して受けるダメージを軽減し、負の効果を受けない可能性を得る。", { scaling: "Lvが上がるほど軽減・無効化が強化", potion: "なし", charm: "未確認" }],
    ["ars_elemental:mist", "霧", "Mist", "Ars Elemental", "有害", "盲目に似た視界制限を与え、見える範囲を狭める。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:repel", "反発", "Repelled", "Ars Elemental", "有害", "魔法の力で対象を指定地点から押し返す。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:rust", "錆", "Rust", "Ars Elemental", "有害", "対象の防具を一時的に劣化させ、防具点を減らす。", { scaling: "Lvが上がるほど防具点の減少が強化", potion: "なし", charm: "未確認" }],
    ["ars_elemental:slip_feet", "滑る足元", "Slippery Feet", "Ars Elemental", "有害", "通常のブロック上でも氷の上のように滑り、移動を制御しにくくする。", { potion: "なし", charm: "未確認" }],
    ["ars_elemental:static_charged", "帯電", "Static Charged", "Ars Elemental", "有害", "効果時間が切れたとき、対象に雷を落とす。", { potion: "Shockポーション系", brewing: "通常・延長Shockポーションあり", charm: "未確認" }],
    ["ars_elemental:venom", "猛毒", "Envenomed", "Ars Elemental", "有害", "通常の毒より強い毒を与え、時間経過で追加ダメージを与える。", { scaling: "Lvが上がるほどダメージが強化", potion: "なし", charm: "未確認" }],
    ["ars_elemental:watery_grave", "水中拘束", "Watery Grave", "Ars Elemental", "有害", "対象を沈ませ、酸素の減少を速める。", { potion: "なし", charm: "未確認" }],
    ["artifacts:magnetism", "磁力", "Magnetism", "Artifacts", "有益", "近くのアイテムエンティティを付与者へ引き寄せる。", { maxLevel: "I", potion: "なし", charm: "既存装備", charmNote: "ArtifactsのUniversal Attractorなど、装備側の固有能力で利用" }],
    ["forbidden_arcanus:spectral_vision", "霊視", "Spectral Vision", "Forbidden Arcanus", "有益", "通常の視界では見えにくい対象や情報を見通すための視覚効果を付与する。", { potion: "なし", charm: "未確認" }],
    ["railcraft:creosote", "クレオソート", "Creosote", "Railcraft Reborn", "有害", "Railcraftのクレオソートに関連する状態を示す。具体的な持続処理は登録クラスとゲーム内の付与側に依存する。", { potion: "なし", charm: "未確認", source: "Railcraft Reborn 1.21.1 jarのeffect登録・langを確認。詳細処理は付与側に依存" }],
    ["relics:immortality", "不死", "Immortality", "Relics", "有益", "致死ダメージを受けても死亡を防ぐRelics専用の状態。", { scaling: "発動条件・再使用待ち時間は付与アイテム側に依存", potion: "なし", charm: "既存装備", charmNote: "Relicsの専用アイテム能力から付与される効果" }],
    ["relics:confusion", "混乱", "Confusion", "Relics", "有害", "操作感や画面表示を乱し、移動・視認を不安定にするRelics専用の状態。", { potion: "なし", charm: "未確認" }],
    ["relics:paralysis", "麻痺", "Paralysis", "Relics", "有害", "対象の行動や移動を止めるRelics専用の状態。", { potion: "なし", charm: "未確認" }],
    ["relics:vanishing", "消失", "Vanishing", "Relics", "有益", "対象を一時的に見えなくするRelics専用の状態。", { potion: "なし", charm: "既存装備", charmNote: "Relics / Reliquified Artifactsの一部能力で発動" }],
    ["relics:anti_heal", "回復阻害", "Anti Heal", "Relics", "有害", "対象が受ける回復を阻害する。", { potion: "なし", charm: "未確認" }],
    ["relics:bleeding", "出血", "Bleeding", "Relics", "有害", "時間経過で出血ダメージを与える。", { scaling: "出血量・間隔は付与アイテム側に依存", potion: "なし", charm: "未確認" }],
    ["relics:glitch", "グリッチ", "Glitch", "Relics", "有害", "対象の表示や挙動にグリッチ系の視覚効果を与える。", { potion: "なし", charm: "未確認" }],
    ["relics:flight", "飛行", "Flight", "Relics", "有益", "プレイヤーに飛行能力を与える。", { maxLevel: "I", potion: "なし", charm: "既存装備", charmNote: "Relicsの飛行能力として付与される効果" }],
    ["relics:tremor", "震動", "Tremor", "Relics", "有害", "対象を揺さぶり、行動や照準を不安定にする。", { potion: "なし", charm: "未確認" }],
    ["relics:stun", "気絶", "Stun", "Relics", "有害", "対象の行動を一時的に止める。", { potion: "なし", charm: "未確認" }],
    ["reliquary:flight", "飛行", "Flight", "Reliquary", "有益", "効果中、クリエイティブ飛行と同様に空中を移動できる。", { maxLevel: "I", potion: "Reliquary専用ポーション", brewing: "Reliquaryのポーション作成システム", charm: "既存装備", charmNote: "Reliquaryの専用ポーション・アイテム効果として付与" }],
    ["reliquary:pacification", "鎮静", "Pacification", "Reliquary", "有益", "敵対的なMobの敵意や攻撃性を抑える。", { potion: "Reliquary専用ポーション", brewing: "Reliquaryのポーション作成システム", charm: "未確認" }],
    ["reliquary:cure", "治療", "Cure", "Reliquary", "有益", "ゾンビ化した村人に付与されている場合、その村人を治療する。", { potion: "Reliquary専用ポーション", duration: "対象への処理後に消費される用途", charm: "未確認" }],
    ["supplementaries:flammable", "可燃化", "Flammable", "Supplementaries", "有害", "燃えている時間を延ばし、歩いた場所へ火を広げる。", { scaling: "Lvが上がるほど燃焼時間・拡散が強化", potion: "なし", charm: "未確認" }],
    ["supplementaries:overencumbered", "過積載", "Overencumbered", "Supplementaries", "有害", "走れなくし、Lvが上がるほどジャンプ高度と歩行速度も下げる。", { scaling: "Lvが上がるほど移動・ジャンプ制限が強化", potion: "なし", charm: "未確認" }],
    ["the_bumblezone:beenergized", "蜂エネルギー", "Beenergized", "The Bumblezone", "有益", "多くの飛行Mobの飛行速度を上げる。Bumblezoneの蜂胸当てを着たプレイヤーは、より長く・遠く飛べる。", { scaling: "Lvによる飛行性能の上昇は付与側に依存", potion: "食べ物などから付与", charm: "未確認" }],
    ["the_bumblezone:hidden", "潜伏", "Hidden", "The Bumblezone", "有益", "敵対Mobが対象を最初に検知する距離を短くする。花粉ブロックの影響でも付与される。", { potion: "通常ポーションなし", charm: "未確認" }],
    ["the_bumblezone:paralyzed", "麻痺", "Paralyzed", "The Bumblezone", "有害", "Mobを動けなくし、多くの場合AIも停止させる。", { potion: "Neurotoxin系の付与側に依存", charm: "未確認" }],
    ["the_bumblezone:protection_of_the_hive", "ハイブの加護", "Protection of the Hive", "The Bumblezone", "有益", "近くの怒った蜂を落ち着かせ、効果中の対象を攻撃した相手へ蜂が反撃する。Wrath of the Hiveからも守るが、その代償で効果を失うことがある。", { potion: "なし", charm: "未確認" }],
    ["the_bumblezone:wrath_of_the_hive", "ハイブの怒り", "Wrath of the Hive", "The Bumblezone", "有害", "Bumblezone内の怒った蜂を強化し、繁殖や幼虫の成長を速める。平和難易度では通常入手できない。", { potion: "通常入手不可", brewing: "醸造不可", charm: "未確認" }],
    ["tombstone:aquatic_life", "水棲生活", "Aquatic Life", "Corail Tombstone", "有益", "水中活動を補助するCorail Tombstoneの効果。細かな処理は付与アイテム・祈りの設定に依存する。", { potion: "専用ポーション候補", charm: "未確認", source: "Corail Tombstone 1.21.1 lang・効果登録キーを確認。詳細処理は付与側のため未確定" }],
    ["tombstone:bait", "餌", "Bait", "Corail Tombstone", "中立", "Mobを引き寄せる餌として働くCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:bone_shield", "骨の盾", "Bone Shield", "Corail Tombstone", "有益", "攻撃を受けたときに骨の盾でダメージを防ぐCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:decrepitude", "老衰", "Decrepitude", "Corail Tombstone", "有害", "身体能力を弱めるCorail Tombstoneの負の効果。具体的な減衰値は付与側に依存する。", { potion: "なし", charm: "未確認" }],
    ["tombstone:discretion", "慎重", "Discretion", "Corail Tombstone", "有益", "敵から気付かれにくくするCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:diversion", "陽動", "Diversion", "Corail Tombstone", "有益", "攻撃対象や敵意をそらすCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:earthly_garden", "地上の庭", "Earthly Garden", "Corail Tombstone", "有益", "周囲の植物・地上環境を利用した回復や成長を補助する効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:feather_fall", "羽根落下", "Feather Fall", "Corail Tombstone", "有益", "落下速度や落下ダメージを抑えるCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:frost_resistance", "凍結耐性", "Frost Resistance", "Corail Tombstone", "有益", "凍結・寒冷に関わるダメージや制限を防ぐCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:frostbite", "凍傷", "Frostbite", "Corail Tombstone", "有害", "対象に寒さ由来のダメージや移動制限を与えるCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:ghostly_shape", "幽体化", "Ghostly Shape", "Corail Tombstone", "有益", "幽体のように攻撃や地形の影響を受けにくくする効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:giant_strength", "巨人の力", "Giant Strength", "Corail Tombstone", "有益", "攻撃力や体格に関わる能力を強化するCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:incurable", "治癒不能", "Incurable", "Corail Tombstone", "有害", "回復や治療の効果を受けにくくするCorail Tombstoneの負の効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:lightning_resistance", "雷耐性", "Lightning Resistance", "Corail Tombstone", "有益", "雷・落雷に関わるダメージを防ぐCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:little_world", "小さな世界", "Little World", "Corail Tombstone", "中立", "周囲の空間や対象サイズに関わるCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:mercy", "慈悲", "Mercy", "Corail Tombstone", "有益", "致命的な状態から対象を救うCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:prayer", "祈り", "Prayer", "Corail Tombstone", "有益", "Corail Tombstoneの祈り・祝福システムを通じて追加効果を与える状態。", { potion: "なし", charm: "未確認" }],
    ["tombstone:preservation", "保存", "Preservation", "Corail Tombstone", "有益", "死亡時のアイテムや状態の保持を補助するCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:projectile_reflection", "飛び道具反射", "Projectile Reflection", "Corail Tombstone", "有益", "飛び道具を反射し、攻撃者側へ返すCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:purification", "浄化", "Purification", "Corail Tombstone", "有益", "対象の負の状態を浄化するCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:reach", "リーチ", "Reach", "Corail Tombstone", "有益", "ブロックやエンティティへ干渉できる距離を広げるCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:remanence", "残留", "Remanence", "Corail Tombstone", "中立", "効果や状態が通常より残りやすくなるCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:restoration", "修復", "Restoration", "Corail Tombstone", "有益", "体力や状態を回復・修復するCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["tombstone:silent_bond", "静かな絆", "Silent Bond", "Corail Tombstone", "有益", "対象と周囲の反応・音に関わるCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:true_sight", "真視", "True Sight", "Corail Tombstone", "有益", "隠された対象や見えにくいものを見通すCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:unstable_intangibility", "不安定な非実体化", "Unstable Intangibility", "Corail Tombstone", "中立", "一時的に実体との衝突を避けるが、安定しないCorail Tombstoneの効果。", { potion: "なし", charm: "未確認" }],
    ["tombstone:weaver_walk", "蜘蛛歩き", "Weaver's Walk", "Corail Tombstone", "有益", "蜘蛛の巣など、通常は移動を妨げる場所を歩きやすくするCorail Tombstoneの効果。", { potion: "専用ポーションあり", charm: "未確認" }],
    ["deeperdarker:sculk_affinity", "スカルク親和", "Sculk Affinity", "Deeper and Darker", "有益", "スカルクや古代都市に関わる探索を補助する効果。詳細な発動条件は付与側に依存する。", { potion: "通常・延長ポーションキーあり", charm: "未確認" }],
    ["deeperdarker:sculk_omen", "スカルクの予兆", "Sculk Omen", "Deeper and Darker", "有害", "スカルク系の脅威やイベントを誘発する予兆状態。詳細挙動は付与側に依存する。", { potion: "通常ポーション未確認", charm: "未確認" }],
    ["eternal_starlight:brittle", "脆弱", "Brittle", "Eternal Starlight", "有害", "受ける凍結ダメージを増加させる。", { scaling: "Lvが上がるほど凍結ダメージ増加が強くなる", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:crystal_infection", "結晶感染", "Crystal Infection", "Eternal Starlight", "有害", "致死性の継続ダメージを与え、防具値も低下させる。", { scaling: "Lvが上がるほど継続ダメージ・防具低下が強化", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:dream_catcher", "夢捕り", "Dream Catcher", "Eternal Starlight", "有益", "防具値を増加させる。", { scaling: "Lvが上がるほど防具値の増加量が大きくなる", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:flammable", "燃えやすさ", "Flammable", "Eternal Starlight", "有害", "受ける火属性ダメージを増加させる。", { scaling: "Lvが上がるほど火属性ダメージ増加が強くなる", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:numbness", "感覚麻痺", "Numbness", "Eternal Starlight", "有害", "受けたダメージの一部を一時的に吸収し、効果終了時にまとめて受ける。", { scaling: "吸収・再適用される量はLvに依存", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:oblivion", "忘却", "Oblivion", "Eternal Starlight", "中立", "壁を通り抜けられるようになり、足元の支持ブロックを失う。しゃがむと下降し、速度・重力・Mobの追跡距離にも影響する。", { potion: "なし", charm: "未確認" }],
    ["eternal_starlight:starfire", "星火", "Starfire", "Eternal Starlight", "有害", "効果の保有者がダメージを受けると周囲のMobにもダメージを与え、死亡時には効果が周囲へ広がる。", { scaling: "周囲へのダメージ・拡散条件はLvに依存", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:sticky", "粘着", "Sticky", "Eternal Starlight", "有害", "移動速度を下げる代わりに、あらゆるブロックを登れるようにする。", { scaling: "Lvが上がるほど移動速度低下が強くなる", potion: "なし", charm: "未確認" }],
    ["eternal_starlight:teary", "涙目", "Teary", "Eternal Starlight", "有害", "視界をぼかし、Mobの攻撃対象指定を解除する。Mobは同じ対象に対して耐性を獲得することがある。", { potion: "なし", charm: "未確認" }],
    ["evilcraft:paling", "青ざめ", "Paling", "EvilCraft", "有害", "EvilCraftのPaling状態を付与する。具体的な持続処理はEvilCraft側の付与手段に依存する。", { potion: "専用アイテム側の付与", charm: "未確認" }],
    ["farmersdelight:comfort", "快適", "Comfort", "Farmer's Delight", "有益", "空腹度に関係なく自然回復できるようにする。", { maxLevel: "I", potion: "なし", charm: "未確認" }],
    ["farmersdelight:nourishment", "滋養", "Nourishment", "Farmer's Delight", "有益", "満腹度が減らなくなる。ただし、隠し満腹度を使う回復など一部の消費は除く。", { maxLevel: "I", potion: "なし", charm: "未確認" }],
    ["twilightforest:frosted", "霜付き", "Frosted", "Twilight Forest", "有害", "Twilight Forestの霜付き状態を付与し、凍結に関わる効果を発生させる。詳細は付与側に依存する。", { potion: "専用アイテム側の付与", charm: "未確認" }],
    ["undergarden:brittleness", "脆さ", "Brittleness", "The Undergarden", "有害", "対象の防具値が高いほど受けるダメージが増える。", { scaling: "Lvが上がるほど防具に対する追加ダメージが強化", potion: "あり", charm: "未確認" }],
    ["undergarden:chilly", "寒気", "Chilly", "The Undergarden", "有害", "移動速度を下げ、画面を揺らす。", { scaling: "Lvが上がるほど移動低下・視覚効果が強化", potion: "なし", charm: "未確認" }],
    ["undergarden:featherweight", "軽量化", "Featherweight", "The Undergarden", "有害", "ダメージを受けた対象が通常より大きく吹き飛ぶ。", { scaling: "Lvが上がるほどノックバック量が増える", potion: "あり", charm: "未確認" }],
    ["undergarden:gooey", "粘液", "Gooey", "The Undergarden", "中立", "対象の足元にScintling Gooを継続的に配置する。", { potion: "なし", charm: "未確認" }],
    ["undergarden:purity", "浄化", "Purity", "The Undergarden", "有益", "毎秒受けるUtheric Infectionの量を減らす。", { scaling: "Lvが上がるほど感染の減少量が増える", potion: "なし", charm: "未確認" }],
    ["undergarden:virulence", "猛毒", "Virulence", "The Undergarden", "有害", "毒に似ているが、より高いダメージをゆっくり与える。Virulent Resistanceで抑えられる。", { scaling: "Lvが上がるほどダメージが強化", potion: "なし", charm: "未確認" }],
    ["undergarden:virulent_resistance", "猛毒耐性", "Virulent Resistance", "The Undergarden", "有益", "Virulenceへの免疫を与える。", { maxLevel: "I", potion: "あり", charm: "未確認" }],
  ].map(([id, ja, en, modName, category, description, options]) => createEffect(id, ja, en, modName, category, description, options));

  const provisionalPrefixes = [
    "tombstone:",
    "deeperdarker:",
    "evilcraft:",
    "railcraft:",
    "twilightforest:",
    "forbidden_arcanus:",
    "relics:",
  ];
  const EFFECTS = [...vanilla, ...custom].map((record) => (
    provisionalPrefixes.some((prefix) => record.id.startsWith(prefix))
      ? { ...record, confidence: "partial" }
      : record
  ));
  window.EFFECTS = EFFECTS;
})();
